In [5]:
import numpy as np

In [6]:
x = [
    [5,-2,2],
    [4,6,-1],
    [-3,1,5]
]

y = [7,8,4]

In [7]:
def dominanceCheck(x):
    x = np.array(x)
    diag = np.diag(np.abs(x))
    not_diag = np.sum(np.abs(x),axis=1) - diag
    if np.all(diag>not_diag):
        return True
    else:
        return False

In [18]:
def gaussSeidel(x,y,e=0.01,n=16):
    if not dominanceCheck(x):
        print("not diagonally dominant")
        return None
    
    x = np.array(x)
    y = np.array(y)

    diag = np.diag(x)
    x = -x
    np.fill_diagonal(x,0)
    mtx_old = np.zeros(x[1].shape)

    for i in range(n):
        mtx_new = np.array(mtx_old)
        for j, row in enumerate(x):
            mtx_new[j] = (y[j]+np.dot(mtx_new,row)) / diag[j]
        print(f"iterasi ke {i+1} adalah: ")
        print(mtx_new)

        euc = np.sqrt(np.dot(mtx_new - mtx_old, mtx_new - mtx_old))

        if euc < e:
            print ("iterasi selesai")
            return
        
        mtx_old = mtx_new

gaussSeidel(x,y)




iterasi ke 1 adalah: 
[1.4  0.4  1.56]
iterasi ke 2 adalah: 
[0.936      0.96933333 1.16773333]
iterasi ke 3 adalah: 
[1.32064    0.64752889 1.46287822]
iterasi ke 4 adalah: 
[1.07386027 0.86123953 1.27206825]
iterasi ke 5 adalah: 
[1.23566851 0.7215657  1.39708796]
iterasi ke 6 adalah: 
[1.1297911  0.81298726 1.3152772 ]
iterasi ke 7 adalah: 
[1.19908402 0.75315685 1.36881904]
iterasi ke 8 adalah: 
[1.15373512 0.79231309 1.33377846]
iterasi ke 9 adalah: 
[1.18341385 0.76668717 1.35671088]
iterasi ke 10 adalah: 
[1.16399052 0.78345813 1.34170268]
iterasi ke 11 adalah: 
[1.17670218 0.77248233 1.35152484]
iterasi ke 12 adalah: 
[1.16838299 0.77966548 1.3450967 ]
iterasi ke 13 adalah: 
[1.17382751 0.77496444 1.34930362]
iterasi selesai
